const P=(n:number)=>`/property-hq/photo-${String(n).padStart(2,"0")}.jpg`;
type Concept="editorial"|"cinematic"|"production";
const nav=[["Home","home"],["The Estate","estate"],["Stay","stay"],["Host an Event","host"],["Gallery","gallery"],["Contact","contact"]];
const concepts:{id:Concept;name:string}[]=[{id:"editorial",name:"01 Editorial"},{id:"cinematic",name:"02 Cinematic"},{id:"production",name:"03 Location"}];
const pageData:Record<string,{eyebrow:string;title:string;intro:string;hero:number}>={
  home:{eyebrow:"PRIVATE HILLSIDE ESTATE · STUDIO CITY",title:"The view is only the beginning.",intro:"A private Los Angeles resort where glass, water, sky, and a remarkable house meet.",hero:1},
  estate:{eyebrow:"THE COMPLETE PROPERTY",title:"Every room finds the view.",intro:"Five bedrooms across three distinct structures, connected by light, landscape, and effortless indoor-outdoor living.",hero:3},
  stay:{eyebrow:"YOUR PRIVATE LOS ANGELES",title:"Check in. Exhale.",intro:"Space for twelve guests, quiet corners for one, and a horizon that belongs entirely to you.",hero:19},
  host:{eyebrow:"GATHER · CREATE · CELEBRATE",title:"Give the moment room to happen.",intro:"A flexible hillside setting for private dinners, productions, retreats, and unforgettable occasions.",hero:10},
  gallery:{eyebrow:"81 VERIFIED PROPERTY IMAGES",title:"The whole story, in view.",intro:"Every image comes directly from the property’s current photography library.",hero:2},
  contact:{eyebrow:"AVAILABILITY · EVENTS · PRODUCTIONS",title:"Tell us what you’re planning.",intro:"Share your dates, headcount, and vision. We’ll return the right information for your stay or event.",hero:4},
};

function Header({concept,page}:{concept:Concept;page:string}){
  return <><div className="concept-rail"><span>CLIENT CONCEPT</span>{concepts.map(c=><a className={c.id===concept?"active":""} key={c.id} href={`/${c.id}/${page==="home"?"":page}`}>{c.name}</a>)}</div><header className="site-header"><a className="wordmark" href={`/${concept}`}><b>WHITE OAK</b><small>7845 TORRISON DRIVE</small></a><nav>{nav.map(([label,slug])=><a className={page===slug?"active":""} key={slug} href={`/${concept}/${slug==="home"?"":slug}`}>{label}</a>)}</nav><a className="inquire-link" href={`/${concept}/contact`}>Inquire ↗</a></header></>
}
function Foot({concept}:{concept:Concept}){return <footer><div className="wordmark"><b>WHITE OAK</b><small>7845 TORRISON DRIVE</small></div><p>STUDIO CITY · CALIFORNIA</p><nav>{nav.map(([x,s])=><a key={s} href={`/${concept}/${s==="home"?"":s}`}>{x}</a>)}</nav></footer>}

function Home({concept}:{concept:Concept}){
  if(concept==="cinematic")return <><section className="cin-home"><img src={P(1)} alt="White Oak estate at blue hour"/><div><p>ONE DAY AT WHITE OAK</p><h1>The city fades.<br/><em>The story begins.</em></h1><span>From first light over the valley to dinner beneath the trees.</span><a href="/cinematic/estate">ENTER THE ESTATE ↓</a></div></section><section className="cin-moments">{[[2,"6:12 PM","THE HORIZON"],[3,"7:04 PM","THE WATER"],[57,"8:26 PM","BENEATH THE OAK"]].map(([n,t,l])=><article key={String(t)}><img src={P(Number(n))} alt={String(l)}/><div><p>{t}</p><h2>{l}</h2></div></article>)}</section></>;
  if(concept==="production")return <><section className="pro-home"><div><p>PRIVATE LOCATION · STUDIO CITY</p><h1>Your next<br/><em>scene is set.</em></h1><span>Panoramic views. Flexible zones. Three structures. Six-car parking. Complete privacy.</span><a href="/production/host">VIEW PRODUCTION USES ↗</a></div><img src={P(1)} alt="Aerial property overview"/></section><section className="pro-stats">{[["12","GUESTS"],["5","BEDROOMS"],["5.5","BATHS"],["6","CARS"],["9 FT","POOL DEPTH"]].map(([a,b])=><div key={b}><b>{a}</b><span>{b}</span></div>)}</section><section className="pro-index">{[["01","ESTATE OVERVIEW","/production/estate",3],["02","STAY CAPACITY","/production/stay",19],["03","EVENT + SHOOT USES","/production/host",10],["04","VISUAL LIBRARY","/production/gallery",2]].map(x=><a key={String(x[0])} href={String(x[2])}><img src={P(Number(x[3]))} alt={String(x[1])}/><span>{x[0]}</span><h2>{x[1]}</h2><b>↗</b></a>)}</section></>;
  return <><section className="ed-home"><div><p>PRIVATE HILLSIDE ESTATE · STUDIO CITY</p><h1>A house with<br/>a <em>point of view.</em></h1><span>A private California resort shaped by glass, light, and a horizon that changes by the hour.</span><a href="/editorial/estate">DISCOVER THE ESTATE ↓</a></div><figure><img src={P(1)} alt="White Oak estate and pool at dusk"/><figcaption>THE ESTATE · BLUE HOUR</figcaption></figure></section><section className="ed-promise"><p>NOT SIMPLY A PLACE TO STAY</p><h2>A private world,<br/><em>above everything.</em></h2><div><span><b>12</b> guests</span><span><b>5</b> bedrooms</span><span><b>5.5</b> baths</span><span><b>180°</b> view</span></div></section><section className="ed-links"><a href="/editorial/estate"><img src={P(3)} alt="Pool terrace"/><span>01</span><h2>The Estate</h2></a><a href="/editorial/stay"><img src={P(19)} alt="Bedroom suite"/><span>02</span><h2>Stay</h2></a><a href="/editorial/host"><img src={P(10)} alt="Event terrace"/><span>03</span><h2>Host</h2></a></section></>;
}

function Estate({concept}:{concept:Concept}){
  const rooms=[["Great Room",12,"A retractable glass wall joins the kitchen, living area, pool, and view."],["Pool Terrace",3,"A nine-foot diving pool, integrated spa, and open-air living above the valley."],["Oak Garden",57,"Mature shade, lawn, and a swing create the estate’s quiet counterpoint."],["Guest House",44,"A separate two-bedroom retreat with its own kitchen, lounge, and terrace."]];
  return <><PageHero concept={concept} page="estate"/><section className={`room-list ${concept}`}>{rooms.map((r,i)=><article key={String(r[0])}><div><span>0{i+1}</span><h2>{r[0]}</h2><p>{r[2]}</p></div><img src={P(Number(r[1]))} alt={String(r[0])}/></article>)}</section><section className="page-cta"><p>THE PROPERTY AT A GLANCE</p><h2>Three structures.<br/>One continuous experience.</h2><a href={`/${concept}/gallery`}>VIEW ALL PHOTOGRAPHY →</a></section></>;
}
function Stay({concept}:{concept:Concept}){
  return <><PageHero concept={concept} page="stay"/><section className={`stay-story ${concept}`}><div><p>ROOM FOR EVERYONE</p><h2>Five bedrooms.<br/>Space to disappear.</h2><span>The main residence and private guest house accommodate up to twelve guests without compromising privacy or calm.</span><a href="https://www.airbnb.com/rooms/1583425609042811538">CHECK AIRBNB AVAILABILITY ↗</a></div><div className="stay-grid">{[19,22,25,31].map((n,i)=><figure key={n}><img src={P(n)} alt={`Bedroom ${i+1}`}/><figcaption>BEDROOM {i+1}</figcaption></figure>)}</div></section><section className="amenities">{[["12","OVERNIGHT GUESTS"],["5","BEDROOMS"],["7","BEDS"],["5.5","BATHROOMS"],["2","KITCHENS"],["6","PARKING SPACES"]].map(([a,b])=><div key={b}><b>{a}</b><span>{b}</span></div>)}</section></>;
}
function Host({concept}:{concept:Concept}){
  const uses=[["Film + Photo",3,"Panoramic sightlines, natural light, varied looks, and support space across three structures."],["Private Events",10,"Pool deck, outdoor kitchen, firepit, garden, and dining zones for moments of every scale."],["Executive Retreats",12,"Overnight capacity, multiple breakout areas, and privacy minutes from the studios."]];
  return <><PageHero concept={concept} page="host"/><section className={`use-cases ${concept}`}>{uses.map((u,i)=><article key={String(u[0])}><img src={P(Number(u[1]))} alt={String(u[0])}/><div><span>0{i+1}</span><h2>{u[0]}</h2><p>{u[2]}</p><a href={`/${concept}/contact`}>START AN INQUIRY ↗</a></div></article>)}</section><section className="logistics"><div><p>LOGISTICS</p><h2>The practical details,<br/>before you need them.</h2></div><ul><li><b>6</b> on-site parking spaces</li><li><b>3</b> separate structures</li><li><b>9 ft</b> diving pool depth</li><li><b>15 min</b> to major studios</li></ul></section></>;
}
function Gallery({concept}:{concept:Concept}){
  const shots=[1,2,3,4,6,8,10,12,15,19,22,25,28,31,35,39,44,48,52,57,61,66,72,78];
  return <><PageHero concept={concept} page="gallery"/><div className={`gallery-grid ${concept}`}>{shots.map((n,i)=><figure key={n}><img src={P(n)} alt={`White Oak property photograph ${i+1}`} loading="lazy"/><figcaption>{String(i+1).padStart(2,"0")} / WHITE OAK</figcaption></figure>)}</div></>;
}
function Contact({concept}:{concept:Concept}){
  return <><PageHero concept={concept} page="contact"/><section className={`contact-form ${concept}`}><div><p>START THE CONVERSATION</p><h2>Stay, gather,<br/>or create.</h2><span>For stays, use the live Airbnb listing. For private events and productions, tell us what you’re planning.</span></div><form action="mailto:hello@whiteoakhollywood.com"><label>Name<input name="name"/></label><label>Email<input type="email" name="email"/></label><label>I’m interested in<select name="interest"><option>A private stay</option><option>Hosting an event</option><option>Film or photography</option><option>An executive retreat</option></select></label><label>Tell us about it<textarea name="message" rows={4}/></label><button>BEGIN AN INQUIRY ↗</button></form></section></>;
}
function PageHero({concept,page}:{concept:Concept;page:string}){const d=pageData[page];return <section className={`page-hero ${concept}`}><img src={P(d.hero)} alt={d.title}/><div><p>{d.eyebrow}</p><h1>{d.title}</h1><span>{d.intro}</span></div></section>}

export function SitePage({concept,page}:{concept:Concept;page:string}){
  const Content=page==="home"?Home:page==="estate"?Estate:page==="stay"?Stay:page==="host"?Host:page==="gallery"?Gallery:Contact;
  return <main className={`site concept-${concept}`}><Header concept={concept} page={page}/><Content concept={concept}/><Foot concept={concept}/></main>
}
