const P=(n:number)=>`/property-hq/photo-${String(n).padStart(2,"0")}.jpg`;
type Concept="editorial"|"cinematic"|"production";
const nav=[["Home","home"],["The Estate","estate"],["Stay","stay"],["Host an Event","host"],["Gallery","gallery"],["Contact","contact"]];
const concepts:{id:Concept;name:string}[]=[{id:"editorial",name:"01 Editorial"},{id:"cinematic",name:"02 Luminous"},{id:"production",name:"03 Dossier"}];
const pageData:Record<string,{eyebrow:string;title:string;intro:string;hero:number}>={
  home:{eyebrow:"PRIVATE HILLSIDE ESTATE · STUDIO CITY",title:"The view is only the beginning.",intro:"A private Los Angeles resort where glass, water, sky, and a remarkable house meet.",hero:1},
  estate:{eyebrow:"THE COMPLETE PROPERTY",title:"Every room finds the view.",intro:"Five bedrooms across three distinct structures, connected by light, landscape, and effortless indoor-outdoor living.",hero:3},
  stay:{eyebrow:"YOUR PRIVATE LOS ANGELES",title:"Check in. Exhale.",intro:"Space for twelve guests, quiet corners for one, and a horizon that belongs entirely to you.",hero:19},
  host:{eyebrow:"GATHER · CREATE · CELEBRATE",title:"Give the moment room to happen.",intro:"A flexible hillside setting for private dinners, productions, retreats, and unforgettable occasions.",hero:10},
  gallery:{eyebrow:"81 VERIFIED PROPERTY IMAGES",title:"The whole story, in view.",intro:"Every image comes directly from the property’s current photography library.",hero:2},
  contact:{eyebrow:"AVAILABILITY · EVENTS · PRODUCTIONS",title:"Tell us what you’re planning.",intro:"Share your dates, headcount, and vision. We’ll return the right information for your stay or event.",hero:4},
};

function Header({concept,page}:{concept:Concept;page:string}){return <><div className="concept-rail"><span>CLIENT CONCEPT</span>{concepts.map(c=><a className={c.id===concept?"active":""} key={c.id} href={`/${c.id}/${page==="home"?"":page}`}>{c.name}</a>)}</div><header className="site-header"><a className="wordmark" href={`/${concept}`}><b>White Oak House</b><small>7845 TORRISON DRIVE</small></a><nav>{nav.slice(1,-1).map(([label,slug])=><a className={page===slug?"active":""} key={slug} href={`/${concept}/${slug}`}>{label}</a>)}</nav><a className="inquire-link" href={`/${concept}/contact`}>Inquire</a></header></>}
function Foot({concept}:{concept:Concept}){return <footer><div className="wordmark"><b>White Oak House</b><small>7845 TORRISON DRIVE</small></div><p>STUDIO CITY · CALIFORNIA</p><nav>{nav.map(([x,s])=><a key={s} href={`/${concept}/${s==="home"?"":s}`}>{x}</a>)}</nav></footer>}

function Home({concept}:{concept:Concept}){
  if(concept==="cinematic")return <div className="luminous-home">
    <section className="lum-hero"><img src={P(2)} alt="Los Angeles panorama from the hillside"/><div><p>CONCEPT 02 · LUMINOUS CINEMA</p><h1>A city away<br/>from the city.</h1><span>At the top of the hill, Los Angeles opens in every direction.</span><a href="#lum-choose">BEGIN THE STORY ↓</a></div></section>
    <section className="lum-arrival"><p>THE ARRIVAL · 5:42 PM</p><h2>It begins the moment<br/>you step out of the car.</h2><span>A private hillside setting above Universal and Studio City—close to everything, removed from all of it.</span></section>
    <section className="lum-choose" id="lum-choose"><p>CHOOSE YOUR STORY</p><div><a href="#lum-shoot"><span>01</span><h2>Shoot</h2><small>Film · photo · music</small></a><a href="#lum-gather"><span>02</span><h2>Gather</h2><small>Corporate · private · considered</small></a><a href="#lum-stay"><span>03</span><h2>Stay</h2><small>Five bedrooms · two residences</small></a></div></section>
    <section className="lum-panorama"><img src={P(4)} alt="View from Torrison Drive at golden hour"/><div><p>THE VIEW · 6:18 PM</p><h2>Nearly 180 degrees<br/>of possibility.</h2></div></section>
    <section className="lum-range"><div><p>ONE LOCATION · MANY LOOKS</p><h2>Light changes.<br/>The house follows.</h2></div>{[12,3,57].map((n,i)=><figure key={n}><img src={P(n)} alt={["Interior living space","Pool terrace","Hillside grounds"][i]}/><figcaption>{["INTERIOR · CLEAN LINES","WATER · OPEN SKY","GROUNDS · QUIET SCALE"][i]}</figcaption></figure>)}</section>
    <section className="lum-chapter lum-shoot" id="lum-shoot"><img src={P(10)} alt="Terrace suitable for production"/><div><p>CREATE · 7:02 PM</p><h2>Your next frame<br/>is already here.</h2><span>Interiors, water, skyline, terraces and changing California light—held inside one private location.</span><a href="/cinematic/host">EXPLORE SHOOT POSSIBILITIES →</a></div></section>
    <section className="lum-chapter lum-gather" id="lum-gather"><img src={P(8)} alt="Pool and terrace prepared for a gathering"/><div><p>GATHER · 7:46 PM</p><h2>Moments with room<br/>to become memorable.</h2><span>For respectful corporate occasions, private dinners and considered celebrations above the city.</span><a href="/cinematic/host">EXPLORE GATHERINGS →</a></div></section>
    <section className="lum-chapter lum-stay" id="lum-stay"><img src={P(19)} alt="Bedroom overlooking the hills"/><div><p>STAY · 9:14 PM</p><h2>Close the doors.<br/>Keep the view.</h2><span>Five bedrooms across the main house and separate guest residence, with the city waiting below.</span><a href="/cinematic/stay">VIEW THE STAY →</a></div></section>
    <section className="lum-proof"><p>THE PROPERTY HAS ALREADY HOSTED</p><div><span>MUSIC VIDEOS</span><span>CREATIVE PRODUCTIONS</span><span>PRIVATE EVENTS</span><span>HIGH-PROFILE GUESTS</span></div><small>Specific credits appear after customer approval.</small></section>
    <section className="lum-close"><img src={P(1)} alt="Pool and fire feature at blue hour"/><div><p>THE INTRODUCTION · 9:48 PM</p><h2>What will you<br/>make of the view?</h2><a href="/cinematic/contact">START A CONVERSATION</a></div></section>
  </div>;
  if(concept==="production")return <div className="dossier-home">
    <section className="dos-hero"><div><p>CONCEPT 03 / LOCATION DOSSIER</p><h1>The house<br/>above the studios.</h1><span>A private Studio City hillside location for productions, respectful gatherings and elevated stays.</span><div><a href="#dos-intents">EXPLORE THE LOCATION ↓</a><a href="/production/contact">REQUEST A SCOUT ↗</a></div></div><img src={P(2)} alt="Torrison Drive view over Los Angeles"/></section>
    <section className="dos-intents" id="dos-intents"><header><span>01 / SELECT PURPOSE</span><h2>What are you planning?</h2></header><div><a href="#dos-shoot"><b>01</b><h3>Shoot</h3><p>Film, television, commercial, music video, photo and content.</p><i>PRIMARY USE →</i></a><a href="#dos-gather"><b>02</b><h3>Gather</h3><p>Corporate days, private dinners and considered celebrations.</p><i>VIEW FIT →</i></a><a href="#dos-stay"><b>03</b><h3>Stay</h3><p>Five bedrooms across the main house and separate ADU.</p><i>VIEW STAY →</i></a></div></section>
    <section className="dos-context"><div><span>02 / LOCATION</span><h2>Central Los Angeles.<br/>Completely removed.</h2><p>Drive one direction into the Valley. Take the other toward West Hollywood. From the property, Universal and Studio City sit below.</p></div><dl><div><dt>VIEW</dt><dd>Nearly 180°</dd></div><div><dt>SETTING</dt><dd>Hilltop</dd></div><div><dt>MAIN HOUSE</dt><dd>Approx. 2,300 sq. ft.</dd></div><div><dt>ADU</dt><dd>Approx. 800 sq. ft.</dd></div></dl></section>
    <section className="dos-looks"><header><span>03 / VISUAL RANGE</span><h2>One address. Multiple looks.</h2></header><div>{[[12,"LIVING / GLASS + LIGHT"],[3,"POOL / SKYLINE"],[15,"KITCHEN / WARM MODERN"],[57,"GROUNDS / HILLSIDE"],[19,"BEDROOM / VIEW"],[1,"NIGHT / CITY GLOW"]].map(([n,t])=><figure key={String(t)}><img src={P(Number(n))} alt={String(t)}/><figcaption>{t}</figcaption></figure>)}</div></section>
    <section className="dos-program" id="dos-shoot"><img src={P(10)} alt="Terrace production setting"/><div><span>04 / PRIMARY PROGRAM</span><h2>Shoot</h2><p>Bring a brief, a camera and a crew. The location supplies skyline, water, interiors, terraces, guest spaces and changing natural light.</p><ul><li>Photo and editorial</li><li>Music video</li><li>Film and television</li><li>Commercial and branded content</li></ul><a href="/production/contact">REQUEST A LOCATION SCOUT →</a></div></section>
    <section className="dos-program reverse" id="dos-gather"><img src={P(8)} alt="Pool terrace for private events"/><div><span>05 / SECONDARY PROGRAM</span><h2>Gather</h2><p>Designed for respectful uses: corporate occasions, private dinners and planned celebrations—not uncontrolled parties.</p><ul><li>Client-stated reasonable threshold: 60–70</li><li>Pool and terrace environment</li><li>Indoor–outdoor flow</li><li>Configuration subject to approval</li></ul><a href="/production/contact">REQUEST AN EVENT PROPOSAL →</a></div></section>
    <section className="dos-program" id="dos-stay"><img src={P(19)} alt="Guest bedroom"/><div><span>06 / SUPPORTING PROGRAM</span><h2>Stay</h2><p>A three-bedroom main residence plus a two-bedroom guest ADU make the location usable beyond a single afternoon.</p><ul><li>Five customer-stated bedrooms</li><li>4.5 customer-stated bathrooms</li><li>Separate guest residence</li><li>Pool/game room</li></ul><a href="/production/stay">VIEW AVAILABILITY →</a></div></section>
    <section className="dos-benefits"><header><span>07 / WHY THIS LOCATION</span><h2>The impression—and the practical potential.</h2></header><div>{[["01","ARRIVAL","A reveal that starts before the front door."],["02","RANGE","Interior, exterior, water, skyline and night."],["03","ACCESS","Between the Valley and West Hollywood."],["04","PRIVACY","A removed hillside feeling in central Los Angeles."],["05","HISTORY","Music videos and events have already used the property."],["06","SUPPORT","A clear inquiry and planning path for every use."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
    <section className="dos-case"><div><span>08 / PROOF FRAMEWORK</span><h2>From location<br/>to finished frame.</h2><p>Approved music-video, influencer and event material will live here as a real case study: brief, property zones used, configuration and result.</p><small>CONCEPT PLACEHOLDER · NO UNAPPROVED CREDIT DISPLAYED</small></div><div className="dos-case-images"><img src={P(57)} alt="Property grounds"/><img src={P(1)} alt="Property at night"/></div></section>
    <section className="dos-faq"><header><span>09 / EARLY QUALIFICATION</span><h2>Before the scout.</h2></header><div><details open><summary>What kinds of productions fit?</summary><p>Photo, film, television, music video, interview and branded-content inquiries are invited. Final fit depends on the brief, crew and schedule.</p></details><details><summary>What kinds of gatherings fit?</summary><p>Respectful corporate and private occasions are the priority. Uncontrolled parties are not the positioning.</p></details><details><summary>How many people?</summary><p>The owner described approximately 60–70 as a reasonable event threshold. Final capacity requires configuration and operational approval.</p></details><details><summary>Can we scout the location?</summary><p>Yes—the concept includes a purpose-built scout request with date flexibility, crew size and project details.</p></details></div><a href="/production/contact">BEGIN A QUALIFIED INQUIRY ↗</a></section>
  </div>;
  return <div className="layout-one">
    <section className="l1-hero"><div className="l1-hero-copy"><p>WORKING NAME · PRIVATE HILLSIDE ESTATE</p><h1>White Oak<br/>House</h1><h2>A city away from the city,<br/>with Los Angeles below.</h2><div className="l1-actions"><a href="/editorial/host">SCOUT THE LOCATION</a><a href="/editorial/contact">PLAN A GATHERING</a></div></div><img src={P(57)} alt="The mature tree and hillside view from the property"/></section>
    <section className="l1-trust" aria-label="Property highlights"><div><i/><p>The Impression:<br/>it begins on arrival</p></div><div><i/><p>The Range:<br/>interiors, water,<br/>skyline and night</p></div><div><i/><p>The Location:<br/>between the Valley<br/>and West Hollywood</p></div></section>
    <section className="l1-purpose"><p>ONE PROPERTY · THREE POSSIBILITIES</p><div><a href="/editorial/host"><span>01</span><h2>Shoot</h2><small>Film · photo · music</small></a><a href="/editorial/contact"><span>02</span><h2>Gather</h2><small>Corporate · private · considered</small></a><a href="/editorial/stay"><span>03</span><h2>Stay</h2><small>Five bedrooms · two residences</small></a></div></section>
    <section className="l1-setting"><img src={P(2)} alt="Panoramic sunset view toward Los Angeles"/><h2>Fifteen minutes from the studios.<br/>A world away.</h2></section>
    <section className="l1-estate"><div className="l1-collage"><img src={P(12)} alt="White Oak living room"/><img src={P(3)} alt="Pool terrace above the valley"/><img src={P(15)} alt="White Oak kitchen"/></div><div className="l1-estate-copy"><p>THE ESTATE</p><h2>Built for light</h2><span>Designed around the oak and the view. Walls of glass. Clean lines. Warm materials. Indoor–outdoor living that feels effortless.</span><a href="/editorial/estate">Explore the estate →</a></div></section>
    <section className="l1-oak"><img src={P(57)} alt="Swing suspended beneath the White Oak tree"/><h2>Every house<br/>has rooms.<br/>This one has<br/>a tree.</h2></section>
    <section className="l1-paths"><a className="host" href="/editorial/host"><img src={P(10)} alt="Evening gathering on the terrace"/><div><h2>Host an Event</h2><p>Film shoots, corporate days,<br/>weddings under the oak.</p><span>LEARN MORE →</span></div></a><a className="stay" href="/editorial/stay"><img src={P(19)} alt="Calm bedroom overlooking the hills"/><div><h2>Stay</h2><p>Nights above the city.</p><span>BOOK A STAY →</span></div></a></section>
    <section className="l1-gallery"><p>GALLERY</p><div>{[28,3,12,2,57,19,15].map((n,i)=><img key={n} src={P(n)} alt={`White Oak gallery preview ${i+1}`}/>)}</div><a href="/editorial/gallery">View Full Gallery →</a></section>
    <section className="l1-proof"><h2>“One of the Hills’ quiet legends”</h2><div><span>ARCHITECTURE</span><span>TRAVEL</span><span>DESIGN</span><span>HOSPITALITY</span></div><small>Editorial positioning shown for concept review; publication credits appear only after approval.</small></section>
    <section className="l1-close"><img src={P(1)} alt="White Oak pool and firepit at blue hour"/><div><h2>The gate opens for few.</h2><a href="/editorial/contact">INQUIRE NOW</a></div></section>
  </div>;
}

function Estate({concept}:{concept:Concept}){const rooms=[["Great Room",12,"A retractable glass wall joins the kitchen, living area, pool, and view."],["Pool Terrace",3,"A nine-foot diving pool, integrated spa, and open-air living above the valley."],["Oak Garden",57,"Mature shade, lawn, and a swing create the estate’s quiet counterpoint."],["Guest House",44,"A separate two-bedroom retreat with its own kitchen, lounge, and terrace."]];return <><PageHero concept={concept} page="estate"/><section className={`room-list ${concept}`}>{rooms.map((r,i)=><article key={String(r[0])}><div><span>0{i+1}</span><h2>{r[0]}</h2><p>{r[2]}</p></div><img src={P(Number(r[1]))} alt={String(r[0])}/></article>)}</section><section className="page-cta"><p>THE PROPERTY AT A GLANCE</p><h2>Three structures.<br/>One continuous experience.</h2><a href={`/${concept}/gallery`}>VIEW ALL PHOTOGRAPHY →</a></section></>}
function Stay({concept}:{concept:Concept}){return <><PageHero concept={concept} page="stay"/><section className={`stay-story ${concept}`}><div><p>ROOM FOR EVERYONE</p><h2>Five bedrooms.<br/>Space to disappear.</h2><span>The main residence and private guest house accommodate up to twelve guests without compromising privacy or calm.</span><a href="https://www.airbnb.com/rooms/1583425609042811538">CHECK AIRBNB AVAILABILITY ↗</a></div><div className="stay-grid">{[19,22,25,31].map((n,i)=><figure key={n}><img src={P(n)} alt={`Bedroom ${i+1}`}/><figcaption>BEDROOM {i+1}</figcaption></figure>)}</div></section><section className="amenities">{[["12","OVERNIGHT GUESTS"],["5","BEDROOMS"],["7","BEDS"],["5.5","BATHROOMS"],["2","KITCHENS"],["6","PARKING SPACES"]].map(([a,b])=><div key={b}><b>{a}</b><span>{b}</span></div>)}</section></>}
function Host({concept}:{concept:Concept}){const uses=[["Film + Photo",3,"Panoramic sightlines, natural light, varied looks, and support space across three structures."],["Private Events",10,"Pool deck, outdoor kitchen, firepit, garden, and dining zones for moments of every scale."],["Executive Retreats",12,"Overnight capacity, multiple breakout areas, and privacy minutes from the studios."]];return <><PageHero concept={concept} page="host"/><section className={`use-cases ${concept}`}>{uses.map((u,i)=><article key={String(u[0])}><img src={P(Number(u[1]))} alt={String(u[0])}/><div><span>0{i+1}</span><h2>{u[0]}</h2><p>{u[2]}</p><a href={`/${concept}/contact`}>START AN INQUIRY ↗</a></div></article>)}</section><section className="logistics"><div><p>LOGISTICS</p><h2>The practical details,<br/>before you need them.</h2></div><ul><li><b>6</b> on-site parking spaces</li><li><b>3</b> separate structures</li><li><b>9 ft</b> diving pool depth</li><li><b>15 min</b> to major studios</li></ul></section></>}
function Gallery({concept}:{concept:Concept}){const shots=[1,2,3,4,6,8,10,12,15,19,22,25,28,31,35,39,44,48,52,57,61,66,72,78];return <><PageHero concept={concept} page="gallery"/><div className={`gallery-grid ${concept}`}>{shots.map((n,i)=><figure key={n}><img src={P(n)} alt={`White Oak property photograph ${i+1}`} loading="lazy"/><figcaption>{String(i+1).padStart(2,"0")} / WHITE OAK</figcaption></figure>)}</div></>}
function Contact({concept}:{concept:Concept}){return <><PageHero concept={concept} page="contact"/><section className={`contact-form ${concept}`}><div><p>START THE CONVERSATION</p><h2>Stay, gather,<br/>or create.</h2><span>For stays, use the live Airbnb listing. For private events and productions, tell us what you’re planning.</span></div><form action="mailto:hello@whiteoakhollywood.com"><label>Name<input name="name"/></label><label>Email<input type="email" name="email"/></label><label>I’m interested in<select name="interest"><option>A private stay</option><option>Hosting an event</option><option>Film or photography</option><option>An executive retreat</option></select></label><label>Tell us about it<textarea name="message" rows={4}/></label><button>BEGIN AN INQUIRY ↗</button></form></section></>}
function PageHero({concept,page}:{concept:Concept;page:string}){const d=pageData[page];return <section className={`page-hero ${concept}`}><img src={P(d.hero)} alt={d.title}/><div><p>{d.eyebrow}</p><h1>{d.title}</h1><span>{d.intro}</span></div></section>}
export function SitePage({concept,page}:{concept:Concept;page:string}){const Content=page==="home"?Home:page==="estate"?Estate:page==="stay"?Stay:page==="host"?Host:page==="gallery"?Gallery:Contact;return <main className={`site concept-${concept}`}><Header concept={concept} page={page}/><Content concept={concept}/><Foot concept={concept}/></main>}
